version: "3.8"
services:
  you-meal_keycloak:
    container_name: you-meal_keycloack
    image: jboss/keycloak:16.1.0
    environment:
      KEYCLOAK_USER: you-meal
      KEYCLOAK_PASSWORD: you-meal
    ports:
      - "8180:8080"
  you-meal_jaeger:
    container_name: you-meal_jaeger
    image: jaegertracing/all-in-one:1.29
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  you-meal_prometheus:
    container_name: you-meal_prometheus
    image: you-meal_prometheus
    ports:
      - "9090:9090"
  you-meal_grafana:
    container_name: you-meal_grafana
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
  you-meal_artemis:
    container_name: you-meal_artemis
    image: vromero/activemq-artemis:2.16.0
    environment:
      ARTEMIS_USERNAME: you-meal
      ARTEMIS_PASSWORD: you-meal
    ports:
      - "8161:8161"
      - "61616:61616"
  you-meal_zookeeper:
    container_name: you-meal_zookeper
    image: debezium/zookeeper:1.9
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  you-meal_kafka:
    container_name: you-meal_kafka
    image: debezium/kafka:1.9
    environment:
      ZOOKEEPER_CONNECT: you-meal_zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - you-meal_zookeeper
  you-meal_kafdrop:
    container_name: you-meal_kafdrop
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
      KAFKA_BROKERCONNECT: you-meal_kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - you-meal_kafka
  you-meal_elasticsearch:
    container_name: you-meal_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_modes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS= -Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memLock:
        soft: -1
        hard: -1
  you-meal_kibana:
    container_name: you-meal_kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    ports:
      - "5601:5601"
  you-meal_registration_postgres:
    container_name: you-meal_registration_postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: you-meal_registration
      POSTGRES_PASSWORD: you-meal_registration
    ports:
      - "5432:5432"
  you-meal_marketplace_postgres:
    container_name: you-meal_marketplace_postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: you-meal_marketplace
      POSTGRES_PASSWORD: you-meal_marketplace
    ports:
      - "5433:5432"
  you-meal_order_mongodb:
    container_name: you-meal_order_mongodb
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: you-meal_order
      MONGO_INITDB_ROOT_PASSWORD: you-meal_order
      MONGO_INITDB_DATABASE: you-meal_order
    ports:
      - "27017:27017"
