CREATE TABLE location
(
    id        INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    latitude  FLOAT8 NULL,
    longitude FLOAT8 NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE restaurant
(
    id            INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    creation_date TIMESTAMP NULL,
    name          VARCHAR(255) NULL,
    "number"      VARCHAR(255) NULL,
    proprietary   VARCHAR(255) NULL,
    update_date   TIMESTAMP NULL,
    location_id   INT8 NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

ALTER TABLE restaurant
    ADD CONSTRAINT fk_restaurant_location_id FOREIGN KEY (location_id) REFERENCES location (id);

CREATE TABLE dish
(
    id            INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description   VARCHAR(255) NULL,
    "name"        VARCHAR(255) NULL,
    price         NUMERIC(19, 2) NULL,
    restaurant_id INT8 NULL,
    CONSTRAINT pk_dish PRIMARY KEY (id)
);

ALTER TABLE dish
    ADD CONSTRAINT fk_dish_restaurant_id FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

CREATE TABLE cart
(
    dish_id INT8         NOT NULL,
    user_id VARCHAR(255) NOT NULL
);